name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: cmake-configure
      uses: snickerbockers/cmake-configure@prerel1
    - name: make all
      run: make all
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
  build-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: cmake-configure
      uses: snickerbockers/cmake-configure@prerel1
    - name: make all
      run: make all
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
